"""Aggregation and rendering of benchmark results.

Turns a directory of JSONL records into the tables and plots a reader needs.
Kept deliberately free of any plotting dependency: it emits Markdown and CSV,
which are reviewable in a pull request. Figures are generated by the scripts in
``experiments/analysis/``, which may depend on matplotlib.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from uniqkache.metrics.record import BenchmarkRecord, validate_record
from uniqkache.utils.errors import ConfigError
from uniqkache.utils.logging import get_logger

_log = get_logger(__name__)

RESULT_GLOBS = ("*.jsonl", "*.json")

# Experiment configs are written next to the results they produced
# (`<name>-<timestamp>.config.json`). They are not records, and they cannot be
# parsed as one: they carry `name`, `runs` and `problems`, and no `run_id`.
# Without this exclusion, a results directory that the runner itself populated
# fails to summarise -- which is the only kind of directory this command is
# pointed at.
EXCLUDED_SUFFIXES = (".config.json",)


def load_records(path: str | Path) -> list[BenchmarkRecord]:
    """Load benchmark records from a file or a directory.

    Supports ``.jsonl`` (one record per line) and ``.json`` (a list of records,
    or a single record).

    Raises
    ------
    ConfigError
        If nothing loadable is found, or a line cannot be parsed. A malformed
        record is reported with its file and line number rather than skipped,
        because a silently dropped record biases any aggregate computed from the
        remainder.
    """
    path = Path(path)
    if not path.exists():
        raise ConfigError(f"results path does not exist: {path}")

    files: list[Path] = []
    if path.is_dir():
        for pattern in RESULT_GLOBS:
            files.extend(sorted(path.glob(pattern)))
        # Deliberately non-recursive: `superseded/` holds withdrawn results, and
        # folding those into a current summary would misreport the project's
        # state. They stay readable by pointing --input at them directly.
        files = [f for f in files if not f.name.endswith(EXCLUDED_SUFFIXES)]
    else:
        files = [path]

    if not files:
        raise ConfigError(
            f"no result files found under {path}. Expected one of: {', '.join(RESULT_GLOBS)}"
        )

    records: list[BenchmarkRecord] = []
    for file in files:
        if file.suffix == ".jsonl":
            for lineno, line in enumerate(file.read_text(encoding="utf-8").splitlines(), 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(BenchmarkRecord.from_dict(json.loads(line)))
                except json.JSONDecodeError as exc:
                    raise ConfigError(f"{file}:{lineno}: invalid JSON: {exc}") from exc
        else:
            payload = json.loads(file.read_text(encoding="utf-8"))
            items = payload if isinstance(payload, list) else [payload]
            records.extend(BenchmarkRecord.from_dict(item) for item in items)

    if not records:
        raise ConfigError(f"no records found under {path}")
    return records


def group_by_policy(records: list[BenchmarkRecord]) -> dict[str, list[BenchmarkRecord]]:
    """Group records by policy name, sorted for stable output."""
    grouped: dict[str, list[BenchmarkRecord]] = defaultdict(list)
    for record in records:
        grouped[record.policy].append(record)
    return {name: grouped[name] for name in sorted(grouped)}


def _fmt(value: float | int | None, unit: str = "", digits: int = 2) -> str:
    """Format a value, rendering ``None`` as ``n/a`` rather than as a number.

    This is what stops an unmeasured metric from appearing in a table as a
    zero and being read as a measured zero.
    """
    if value is None:
        return "n/a"
    if isinstance(value, int):
        return f"{value}{unit}"
    return f"{value:.{digits}f}{unit}"


def records_to_markdown(records: list[BenchmarkRecord], *, title: str = "Benchmark results") -> str:
    """Render records as a Markdown table with a quality column.

    The quality column is mandatory in the output. A table of memory and latency
    without quality is exactly the artefact this project exists to avoid, so the
    renderer always emits it even when every value is ``n/a``.
    """
    if not records:
        return f"# {title}\n\n_No records._\n"

    lines = [
        f"# {title}",
        "",
        f"{len(records)} run(s) across {len(group_by_policy(records))} policy/policies.",
        "",
        "| policy | model | ctx | cap | sink | precision | device | "
        "peak mem | cache mem | compr. | TTFT (ms) | TPOT (ms) | tok/s | quality |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]

    for record in sorted(records, key=lambda r: (r.policy, r.context_length or 0)):
        quality = "n/a"
        if record.quality_metric and record.quality_value is not None:
            quality = f"{record.quality_metric}={record.quality_value:.4f}"
            if not record.weights_are_random:
                delta = record.quality_delta
                if delta is not None:
                    quality += f" ({delta:+.4f})"
            else:
                quality += " *(random weights)*"

        lines.append(
            "| {policy} | {model} | {ctx} | {cap} | {sink} | {precision} | {device} | "
            "{peak} | {cache} | {ratio} | {ttft} | {tpot} | {tps} | {quality} |".format(
                policy=record.policy,
                model=record.model,
                ctx=_fmt(record.context_length),
                cap="unbounded" if record.capacity is None else str(record.capacity),
                sink=record.attention_sinks,
                precision=record.precision,
                device=record.device,
                peak=_fmt(
                    None
                    if record.peak_memory_bytes is None
                    else record.peak_memory_bytes / 1024**2,
                    " MiB",
                ),
                cache=_fmt(
                    None
                    if record.cache_bytes_total is None
                    else record.cache_bytes_total / 1024**2,
                    " MiB",
                ),
                ratio=_fmt(record.cache_compression_ratio, "x"),
                ttft=_fmt(record.ttft_ms),
                tpot=_fmt(record.tpot_ms, digits=3),
                tps=_fmt(record.tokens_per_second, digits=1),
                quality=quality,
            )
        )

    problems: list[str] = []
    for record in records:
        for problem in validate_record(record):
            problems.append(f"- `{record.run_id}` ({record.policy}): {problem}")
    if problems:
        lines.extend(["", "## Integrity warnings", ""])
        lines.extend(problems)

    return "\n".join(lines) + "\n"


def records_to_csv(records: list[BenchmarkRecord], destination: str | Path) -> Path:
    """Write records to CSV, flattening nested fields rather than dropping them."""
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not records:
        raise ConfigError("no records to write")

    rows = [record.to_flat_dict() for record in records]
    # Union of keys across rows, so a field present in one run is not lost.
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    with destination.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return destination


def summarize(records: list[BenchmarkRecord]) -> dict[str, Any]:
    """Compute a small aggregate summary across records."""
    grouped = group_by_policy(records)
    out: dict[str, Any] = {"total_runs": len(records), "policies": {}}
    for policy, group in grouped.items():
        peaks = [r.peak_memory_bytes for r in group if r.peak_memory_bytes is not None]
        caches = [r.cache_bytes_total for r in group if r.cache_bytes_total is not None]
        ttfts = [r.ttft_ms for r in group if r.ttft_ms is not None]
        qualities = [r.quality_value for r in group if r.quality_value is not None]
        out["policies"][policy] = {
            "runs": len(group),
            "mean_peak_memory_bytes": sum(peaks) / len(peaks) if peaks else None,
            "mean_cache_bytes": sum(caches) / len(caches) if caches else None,
            "mean_ttft_ms": sum(ttfts) / len(ttfts) if ttfts else None,
            "mean_quality": sum(qualities) / len(qualities) if qualities else None,
        }
    return out


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m uniqkache.metrics.report",
        description="Summarise UniqKache benchmark results into tables.",
    )
    parser.add_argument("--input", required=True, help="Results file or directory")
    parser.add_argument(
        "--format",
        default="markdown",
        choices=["markdown", "csv", "json"],
        help="Output format",
    )
    parser.add_argument("--output", default=None, help="Output path; stdout when omitted")
    parser.add_argument("--title", default="Benchmark results", help="Markdown title")
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    args = build_parser().parse_args(argv)

    try:
        records = load_records(args.input)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.format == "markdown":
        rendered = records_to_markdown(records, title=args.title)
        if args.output:
            Path(args.output).write_text(rendered, encoding="utf-8")
            print(f"wrote {args.output}")
        else:
            print(rendered)
    elif args.format == "json":
        payload = json.dumps(
            {"summary": summarize(records), "records": [r.to_dict() for r in records]},
            indent=2,
        )
        if args.output:
            Path(args.output).write_text(payload, encoding="utf-8")
            print(f"wrote {args.output}")
        else:
            print(payload)
    else:
        if not args.output:
            print("error: --output is required for CSV", file=sys.stderr)
            return 2
        destination = records_to_csv(records, args.output)
        print(f"wrote {destination}")

    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())


__all__ = [
    "group_by_policy",
    "load_records",
    "main",
    "records_to_csv",
    "records_to_markdown",
    "summarize",
]
